import './cards.html';
import './create-beach-form.html';
import './create-hike-form.html';
import './create-restaurant-form.html';
import './create-beach-form.js';
import './create-hike-form.js';
import './create-restaurant-form.js';
import './filter.html';
import './filter.js';
